export const appConfig = Object.freeze({
  name: "Bahasa Melayu Mastery",
  subtitle: "Daripada Perkataan kepada Karangan",
  language: "ms-MY",
  curriculum: "master-2026",
  contentVersion: "2026",
  flags: { ai: true, speech: true, story: true },
  years: [1, 2, 3, 4, 5, 6].map((year) => ({ year, label: `Tahun ${year}` })),
});
export const navigation = [
  { id: "home", label: "Utama", icon: "home" },
  {
    id: "vocabulary",
    label: "Bank Kata & Frasa",
    icon: "book",
    description: "Kenali perkataan, temui makna baharu.",
    color: "coral",
    step: "01",
    tag: "KENALI",
  },
  {
    id: "sentence",
    label: "Bina Ayat",
    icon: "pencil",
    description: "Susun idea menjadi ayat bermakna.",
    color: "blue",
    step: "02",
    tag: "BINA",
  },
  {
    id: "expansion",
    label: "Kembangkan Ayat",
    icon: "sprout",
    description: "Hidupkan ayat dengan butiran yang sesuai.",
    color: "orange",
    step: "03",
    tag: "KEMBANGKAN",
  },
  {
    id: "paragraph",
    label: "Bina Perenggan",
    icon: "align",
    description: "Hubungkan ayat, kembangkan satu idea.",
    color: "purple",
    step: "04",
    tag: "HUBUNGKAN",
  },
  {
    id: "essay",
    label: "Karangan Berpandu",
    icon: "file",
    description: "Dari rancangan kecil kepada cerita sendiri.",
    color: "rose",
    step: "05",
    tag: "KARANG",
  },
  {
    id: "story",
    label: "Rantai Cerita",
    icon: "spark",
    description: "Sambung cerita, terokai imaginasi.",
    color: "yellow",
    step: "06",
    tag: "CIPTA",
  },
  { id: "practice", label: "Latihan Ejaan & Imlak", icon: "sound", description: "Dengar, cuba dan semak tulisan kamu.", color: "blue", step: "07", tag: "LATIH" },
  { id: "drafts", label: "Draf Saya", icon: "folder" },
];
export const labels = {
  demo: "DEMO",
  saved: "Disimpan pada peranti ini",
  temporary: "Simpanan sementara sahaja — muat turun draf sebelum keluar.",
  writing: "Penulisan saya",
  teacher: "Cikgu AI",
  close: "Tutup",
  empty: "Belum ada draf. Idea pertama anda bermula dengan satu ayat.",
};
export const scaffoldFields = [
  ["who", "Siapa / Apa?"],
  ["action", "Buat apa?"],
  ["where", "Di mana?"],
  ["when", "Bila?"],
  ["how", "Bagaimana?"],
  ["why", "Mengapa?"],
];
export const essayStages = [
  "Fikir",
  "Rancang idea",
  "Pilih kata/frasa",
  "Tulis sendiri",
  "Dapatkan bimbingan AI",
  "Baiki sendiri",
  "Perenggan seterusnya",
  "Semak keseluruhan karangan",
];
